/**
 * Project: Smart Multi-Compartment Grocery Delivery System
 * Author: Ahmed Alasiri
 * Institution: King Khalid University (2026)
 * Description: IoT-based logistics hub featuring climate control and automated transport.
 */

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4pzRJpCpY3qZkTgg9vye_ofVB0pTgLno',
    appId: '1:541906426214:web:f5532aa43ce8465ce4d0a7',
    messagingSenderId: '541906426214',
    projectId: 'kku-smcs',
    authDomain: 'kku-smcs.firebaseapp.com',
    storageBucket: 'kku-smcs.firebasestorage.app',
    measurementId: 'G-7V7EKHWZN8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSiCa2Hm3bXvEbbu_5BpHNR-FsKPWqXO0',
    appId: '1:541906426214:android:1c4b8a901f5b9c52e4d0a7',
    messagingSenderId: '541906426214',
    projectId: 'kku-smcs',
    storageBucket: 'kku-smcs.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPhTNZolgp4xSpe4JXNQADEGxA74uj8Bo',
    appId: '1:541906426214:ios:0fee782378d0673ce4d0a7',
    messagingSenderId: '541906426214',
    projectId: 'kku-smcs',
    storageBucket: 'kku-smcs.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPhTNZolgp4xSpe4JXNQADEGxA74uj8Bo',
    appId: '1:541906426214:ios:0fee782378d0673ce4d0a7',
    messagingSenderId: '541906426214',
    projectId: 'kku-smcs',
    storageBucket: 'kku-smcs.firebasestorage.app',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4pzRJpCpY3qZkTgg9vye_ofVB0pTgLno',
    appId: '1:541906426214:web:e93dbc0c1ddb2205e4d0a7',
    messagingSenderId: '541906426214',
    projectId: 'kku-smcs',
    authDomain: 'kku-smcs.firebaseapp.com',
    storageBucket: 'kku-smcs.firebasestorage.app',
    measurementId: 'G-8KG1Q4ELMX',
  );
}
